### ISSUE TITLE
No drop down for city on new job

### ISSUE THREAD

**Issue by vigeeking** [msaperst/snnap#689]
It says "please select a valid city from the drop down" but there's no drop down
![image](https://user-images.githubusercontent.com/54846818/207691422-6ab8c149-4185-4d8d-a3b1-b43d2901d5dd.png)
Also, years aren't capped, but I'm not sure if that's as desired.  I can book something for the year 5000

**Comment by msaperst** [comment]
yeah, it's an auto-complete drop down, not a traditional drop down. Maybe the error message needs to be better, or do you just not see it at all?
![image](https://user-images.githubusercontent.com/2692269/207706050-46da9ec4-dd31-46c8-87ac-3d509cc45ea9.png)

**Comment by vigeeking** [comment]
User error, not sure why I didn't register that before, my bad.
